#pragma once
#include "macro.h"

#define RTL_PREFIX jit

#define rtl_li name_concat(RTL_PREFIX, _rtl_li)
#define rtl_mv name_concat(RTL_PREFIX, _rtl_mv)
#define rtl_add name_concat(RTL_PREFIX, _rtl_add)
#define rtl_sub name_concat(RTL_PREFIX, _rtl_sub)
#define rtl_and name_concat(RTL_PREFIX, _rtl_and)
#define rtl_or name_concat(RTL_PREFIX, _rtl_or)
#define rtl_xor name_concat(RTL_PREFIX, _rtl_xor)
#define rtl_shl name_concat(RTL_PREFIX, _rtl_shl)
#define rtl_shr name_concat(RTL_PREFIX, _rtl_shr)
#define rtl_sar name_concat(RTL_PREFIX, _rtl_sar)
#define rtl_mul_lo name_concat(RTL_PREFIX, _rtl_mul_lo)
#define rtl_mul_hi name_concat(RTL_PREFIX, _rtl_mul_hi)
#define rtl_imul_lo name_concat(RTL_PREFIX, _rtl_imul_lo)
#define rtl_imul_hi name_concat(RTL_PREFIX, _rtl_imul_hi)
#define rtl_div_q name_concat(RTL_PREFIX, _rtl_div_q)
#define rtl_div_r name_concat(RTL_PREFIX, _rtl_div_r)
#define rtl_idiv_q name_concat(RTL_PREFIX, _rtl_idiv_q)
#define rtl_idiv_r name_concat(RTL_PREFIX, _rtl_idiv_r)
#define rtl_div64_q name_concat(RTL_PREFIX, _rtl_div64_q)
#define rtl_div64_r name_concat(RTL_PREFIX, _rtl_div64_r)
#define rtl_idiv64_q name_concat(RTL_PREFIX, _rtl_idiv64_q)
#define rtl_idiv64_r name_concat(RTL_PREFIX, _rtl_idiv64_r)
#define rtl_lm name_concat(RTL_PREFIX, _rtl_lm)
#define rtl_sm name_concat(RTL_PREFIX, _rtl_sm)
// #define rtl_host_lm name_concat(RTL_PREFIX, _rtl_host_lm)
// #define rtl_host_sm name_concat(RTL_PREFIX, _rtl_host_sm)
#define rtl_setrelop name_concat(RTL_PREFIX, _rtl_setrelop)
#define rtl_j name_concat(RTL_PREFIX, _rtl_j)
#define rtl_jr name_concat(RTL_PREFIX, _rtl_jr)
#define rtl_jcond name_concat(RTL_PREFIX, _rtl_jcond)

#define rtl_active name_concat(RTL_PREFIX, _rtl_active)
#define rtl_exit name_concat(RTL_PREFIX, _rtl_exit)
